# Change these first
owner: QuintixLabs # Your GitHub organization or username, where this repository lives
repo: voux-instances-uptime # The name of this repository

sites:
  - name: voux.fr0st.xyz
    url: https://voux.fr0st.xyz/
    expectedStatusCodes:
      - 200
      - 201
      - 202
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Voux Instances
  introTitle: "Uptime for all the **Voux** instances"
  introMessage: This page shows the status of all [Voux](https://github.com/QuintixLabs/Voux) instance
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
